### ISSUE TITLE
Multiable Servers Manager wont work with rcon tool

### ISSUE THREAD

**Issue by yolarrydabomb** [jaron780/RconTool#3]
I have 2 servers. one on 11775/11776 and another 11778/11779 and they don't change/flip each line I pick on.

**Comment by jaron780** [comment]
make sure the ports are forwarded correctly and entered correctly in the tool

**Comment by Doge117** [comment]
I did. It will only open server 1. It won't go to server 2. even if I reopen the app.

**Comment by yolarrydabomb** [comment]
Sorry Let me clarify better. I used you server manager box to add 2 servers on the list but for some reason it won't click or go to the second server. it keeps opening the first server from the manager list. I closed your app and reopen it and still won't select my 11778 server. I have to edit the first line each time or make separate folders of your app 

All ports is forward and working. I even test it with web rcon and joined the game. It's not my server...Its on a VPS. The config file does have both listed. I just can't select second one down.

**Comment by Zentillion** [comment]
Same issue here. I run three servers and the only way to access them is to change the ports in the server manager every time.

**Comment by jaron780** [comment]
You have to use the slider at the bottom of the program to select between viewing each server

**Comment by yolarrydabomb** [comment]
Ahh I see. I thought it was something to do with refresh speed. lol
